scrape_configs:
  - job_name: minecraft
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:9400
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090